// Code generated by enumerator. DO NOT EDIT.

package drive

import (
	"database/sql/driver"
	"fmt"
)

type DriveVisibility struct {
	v driveVisibilityEnum
}

var (
	DriveVisibilityPublic = DriveVisibility{driveVisibilityPublic}
	DriveVisibilityMember = DriveVisibility{driveVisibilityMember}
	DriveVisibilityAdmin  = DriveVisibility{driveVisibilityAdmin}
)

func (r DriveVisibility) Format(f fmt.State, verb rune) {
	switch verb {
	case 's':
		fmt.Fprint(f, r.v)
	case 'q':
		fmt.Fprintf(f, "%q", r.String())
	default:
		fmt.Fprint(f, r.v)
	}
}
func (r DriveVisibility) String() string {
	return string(r.v)
}
func (r DriveVisibility) MarshalText() ([]byte, error) {
	return []byte(r.v), nil
}
func (r *DriveVisibility) UnmarshalText(__iNpUt__ []byte) error {
	s, err := NewDriveVisibility(string(__iNpUt__))
	if err != nil {
		return err
	}
	*r = s
	return nil
}
func (r DriveVisibility) Value() (driver.Value, error) {
	return r.v, nil
}
func (r *DriveVisibility) Scan(__iNpUt__ any) error {
	s, err := NewDriveVisibility(fmt.Sprint(__iNpUt__))
	if err != nil {
		return err
	}
	*r = s
	return nil
}
func NewDriveVisibility(__iNpUt__ string) (DriveVisibility, error) {
	switch __iNpUt__ {
	case string(driveVisibilityPublic):
		return DriveVisibilityPublic, nil
	case string(driveVisibilityMember):
		return DriveVisibilityMember, nil
	case string(driveVisibilityAdmin):
		return DriveVisibilityAdmin, nil
	default:
		return DriveVisibility{}, fmt.Errorf("invalid value for type 'DriveVisibility': '%s'", __iNpUt__)
	}
}
