/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import useSwr from "swr";
import type { Arguments, Key, SWRConfiguration } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";

import { fetcher } from "../client";
import type {
  AdminDriveFolderCreateBody,
  AdminDriveFolderUpdateBody,
  BadRequestResponse,
  DriveFileDownloadOKResponse,
  DriveFileDownloadParams,
  DriveFolderContentsOKResponse,
  DriveFolderContentsParams,
  DriveFolderGetOKResponse,
  DriveFolderListOKResponse,
  InternalServerErrorResponse,
  NotFoundResponse,
  UnauthorisedResponse,
} from "../openapi-schema";

/**
 * List every Google Drive folder registered on this installation,
including those hidden from ordinary members.

 */
export const adminDriveFolderList = () => {
  return fetcher<DriveFolderListOKResponse>({
    url: `/admin/drive/folders`,
    method: "GET",
  });
};

export const getAdminDriveFolderListKey = () =>
  [`/admin/drive/folders`] as const;

export type AdminDriveFolderListQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminDriveFolderList>>
>;
export type AdminDriveFolderListQueryError =
  | UnauthorisedResponse
  | InternalServerErrorResponse;

export const useAdminDriveFolderList = <
  TError = UnauthorisedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof adminDriveFolderList>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
}) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getAdminDriveFolderListKey() : null));
  const swrFn = () => adminDriveFolderList();

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
/**
 * Register a Google Drive folder so members can browse it. The folder must
already be shared with the installation's service account.

 */
export const adminDriveFolderCreate = (
  adminDriveFolderCreateBody: AdminDriveFolderCreateBody,
) => {
  return fetcher<DriveFolderGetOKResponse>({
    url: `/admin/drive/folders`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: adminDriveFolderCreateBody,
  });
};

export const getAdminDriveFolderCreateMutationFetcher = () => {
  return (
    _: Key,
    { arg }: { arg: AdminDriveFolderCreateBody },
  ): Promise<DriveFolderGetOKResponse> => {
    return adminDriveFolderCreate(arg);
  };
};
export const getAdminDriveFolderCreateMutationKey = () =>
  [`/admin/drive/folders`] as const;

export type AdminDriveFolderCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminDriveFolderCreate>>
>;
export type AdminDriveFolderCreateMutationError =
  | BadRequestResponse
  | UnauthorisedResponse
  | InternalServerErrorResponse;

export const useAdminDriveFolderCreate = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof adminDriveFolderCreate>>,
    TError,
    Key,
    AdminDriveFolderCreateBody,
    Awaited<ReturnType<typeof adminDriveFolderCreate>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAdminDriveFolderCreateMutationKey();
  const swrFn = getAdminDriveFolderCreateMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Change a registered Google Drive folder.
 */
export const adminDriveFolderUpdate = (
  driveFolderId: string,
  adminDriveFolderUpdateBody: AdminDriveFolderUpdateBody,
) => {
  return fetcher<DriveFolderGetOKResponse>({
    url: `/admin/drive/folders/${driveFolderId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: adminDriveFolderUpdateBody,
  });
};

export const getAdminDriveFolderUpdateMutationFetcher = (
  driveFolderId: string,
) => {
  return (
    _: Key,
    { arg }: { arg: AdminDriveFolderUpdateBody },
  ): Promise<DriveFolderGetOKResponse> => {
    return adminDriveFolderUpdate(driveFolderId, arg);
  };
};
export const getAdminDriveFolderUpdateMutationKey = (driveFolderId: string) =>
  [`/admin/drive/folders/${driveFolderId}`] as const;

export type AdminDriveFolderUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminDriveFolderUpdate>>
>;
export type AdminDriveFolderUpdateMutationError =
  | BadRequestResponse
  | UnauthorisedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

export const useAdminDriveFolderUpdate = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  driveFolderId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof adminDriveFolderUpdate>>,
      TError,
      Key,
      AdminDriveFolderUpdateBody,
      Awaited<ReturnType<typeof adminDriveFolderUpdate>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getAdminDriveFolderUpdateMutationKey(driveFolderId);
  const swrFn = getAdminDriveFolderUpdateMutationFetcher(driveFolderId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Withdraw a Google Drive folder from the site. Nothing is removed from
Google Drive itself.

 */
export const adminDriveFolderDelete = (driveFolderId: string) => {
  return fetcher<void>({
    url: `/admin/drive/folders/${driveFolderId}`,
    method: "DELETE",
  });
};

export const getAdminDriveFolderDeleteMutationFetcher = (
  driveFolderId: string,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<void> => {
    return adminDriveFolderDelete(driveFolderId);
  };
};
export const getAdminDriveFolderDeleteMutationKey = (driveFolderId: string) =>
  [`/admin/drive/folders/${driveFolderId}`] as const;

export type AdminDriveFolderDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminDriveFolderDelete>>
>;
export type AdminDriveFolderDeleteMutationError =
  | UnauthorisedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

export const useAdminDriveFolderDelete = <
  TError =
    | UnauthorisedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  driveFolderId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof adminDriveFolderDelete>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof adminDriveFolderDelete>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getAdminDriveFolderDeleteMutationKey(driveFolderId);
  const swrFn = getAdminDriveFolderDeleteMutationFetcher(driveFolderId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * List the Google Drive folders the caller may browse. Folders are
filtered by the visibility an administrator assigned to each one.

 */
export const driveFolderList = () => {
  return fetcher<DriveFolderListOKResponse>({
    url: `/drive/folders`,
    method: "GET",
  });
};

export const getDriveFolderListKey = () => [`/drive/folders`] as const;

export type DriveFolderListQueryResult = NonNullable<
  Awaited<ReturnType<typeof driveFolderList>>
>;
export type DriveFolderListQueryError = InternalServerErrorResponse;

export const useDriveFolderList = <
  TError = InternalServerErrorResponse,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof driveFolderList>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
}) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getDriveFolderListKey() : null));
  const swrFn = () => driveFolderList();

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
/**
 * List the contents of a registered folder, or of a folder beneath it.
Any folder outside the registered root is reported as not found.

 */
export const driveFolderContents = (
  driveFolderId: string,
  params?: DriveFolderContentsParams,
) => {
  return fetcher<DriveFolderContentsOKResponse>({
    url: `/drive/folders/${driveFolderId}/contents`,
    method: "GET",
    params,
  });
};

export const getDriveFolderContentsKey = (
  driveFolderId: string,
  params?: DriveFolderContentsParams,
) =>
  [
    `/drive/folders/${driveFolderId}/contents`,
    ...(params ? [params] : []),
  ] as const;

export type DriveFolderContentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof driveFolderContents>>
>;
export type DriveFolderContentsQueryError =
  | NotFoundResponse
  | InternalServerErrorResponse;

export const useDriveFolderContents = <
  TError = NotFoundResponse | InternalServerErrorResponse,
>(
  driveFolderId: string,
  params?: DriveFolderContentsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof driveFolderContents>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!driveFolderId;
  const swrKey =
    swrOptions?.swrKey ??
    (() =>
      isEnabled ? getDriveFolderContentsKey(driveFolderId, params) : null);
  const swrFn = () => driveFolderContents(driveFolderId, params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
/**
 * Stream a file's contents through the site. Google-native documents are
exported to a portable format first. Any file outside the registered
root is reported as not found.

 */
export const driveFileDownload = (
  driveFolderId: string,
  driveFileId: string,
  params?: DriveFileDownloadParams,
) => {
  return fetcher<DriveFileDownloadOKResponse>({
    url: `/drive/folders/${driveFolderId}/files/${driveFileId}/content`,
    method: "GET",
    params,
  });
};

export const getDriveFileDownloadKey = (
  driveFolderId: string,
  driveFileId: string,
  params?: DriveFileDownloadParams,
) =>
  [
    `/drive/folders/${driveFolderId}/files/${driveFileId}/content`,
    ...(params ? [params] : []),
  ] as const;

export type DriveFileDownloadQueryResult = NonNullable<
  Awaited<ReturnType<typeof driveFileDownload>>
>;
export type DriveFileDownloadQueryError =
  | NotFoundResponse
  | InternalServerErrorResponse;

export const useDriveFileDownload = <
  TError = NotFoundResponse | InternalServerErrorResponse,
>(
  driveFolderId: string,
  driveFileId: string,
  params?: DriveFileDownloadParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof driveFileDownload>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled =
    swrOptions?.enabled !== false && !!(driveFolderId && driveFileId);
  const swrKey =
    swrOptions?.swrKey ??
    (() =>
      isEnabled
        ? getDriveFileDownloadKey(driveFolderId, driveFileId, params)
        : null);
  const swrFn = () => driveFileDownload(driveFolderId, driveFileId, params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
