/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import useSwr from "swr";
import type { Arguments, Key, SWRConfiguration } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";

import { fetcher } from "../client";
import type {
  BadRequestResponse,
  ForbiddenResponse,
  InternalServerErrorResponse,
  NotFoundResponse,
  TagCreateBody,
  TagCreateOKResponse,
  TagGetOKResponse,
  TagListOKResponse,
  TagListParams,
  TagUpdateBody,
  TagUpdateOKResponse,
  UnauthorisedResponse,
} from "../openapi-schema";

/**
 * Get a list of all tags on the site.
 */
export const tagList = (params?: TagListParams) => {
  return fetcher<TagListOKResponse>({ url: `/tags`, method: "GET", params });
};

export const getTagListKey = (params?: TagListParams) =>
  [`/tags`, ...(params ? [params] : [])] as const;

export type TagListQueryResult = NonNullable<
  Awaited<ReturnType<typeof tagList>>
>;
export type TagListQueryError = InternalServerErrorResponse;

export const useTagList = <TError = InternalServerErrorResponse>(
  params?: TagListParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof tagList>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getTagListKey(params) : null));
  const swrFn = () => tagList(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
/**
 * Create a new tag. Visible to staff/moderators.
 */
export const tagCreate = (tagCreateBody: TagCreateBody) => {
  return fetcher<TagCreateOKResponse>({
    url: `/tags`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tagCreateBody,
  });
};

export const getTagCreateMutationFetcher = () => {
  return (
    _: Key,
    { arg }: { arg: TagCreateBody },
  ): Promise<TagCreateOKResponse> => {
    return tagCreate(arg);
  };
};
export const getTagCreateMutationKey = () => [`/tags`] as const;

export type TagCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tagCreate>>
>;
export type TagCreateMutationError =
  | BadRequestResponse
  | UnauthorisedResponse
  | ForbiddenResponse
  | InternalServerErrorResponse;

export const useTagCreate = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | ForbiddenResponse
    | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof tagCreate>>,
    TError,
    Key,
    TagCreateBody,
    Awaited<ReturnType<typeof tagCreate>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getTagCreateMutationKey();
  const swrFn = getTagCreateMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Get information about a tag.
 */
export const tagGet = (tagName: string) => {
  return fetcher<TagGetOKResponse>({ url: `/tags/${tagName}`, method: "GET" });
};

export const getTagGetKey = (tagName: string) => [`/tags/${tagName}`] as const;

export type TagGetQueryResult = NonNullable<Awaited<ReturnType<typeof tagGet>>>;
export type TagGetQueryError = NotFoundResponse | InternalServerErrorResponse;

export const useTagGet = <
  TError = NotFoundResponse | InternalServerErrorResponse,
>(
  tagName: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof tagGet>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!tagName;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getTagGetKey(tagName) : null));
  const swrFn = () => tagGet(tagName);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
/**
 * Delete a tag by name. Visible to staff/moderators.
 */
export const tagDelete = (tagName: string) => {
  return fetcher<void>({ url: `/tags/${tagName}`, method: "DELETE" });
};

export const getTagDeleteMutationFetcher = (tagName: string) => {
  return (_: Key, __: { arg: Arguments }): Promise<void> => {
    return tagDelete(tagName);
  };
};
export const getTagDeleteMutationKey = (tagName: string) =>
  [`/tags/${tagName}`] as const;

export type TagDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof tagDelete>>
>;
export type TagDeleteMutationError =
  | UnauthorisedResponse
  | ForbiddenResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

export const useTagDelete = <
  TError =
    | UnauthorisedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  tagName: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof tagDelete>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof tagDelete>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getTagDeleteMutationKey(tagName);
  const swrFn = getTagDeleteMutationFetcher(tagName);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Update/rename a tag by name. Visible to staff/moderators.
 */
export const tagUpdate = (tagName: string, tagUpdateBody: TagUpdateBody) => {
  return fetcher<TagUpdateOKResponse>({
    url: `/tags/${tagName}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: tagUpdateBody,
  });
};

export const getTagUpdateMutationFetcher = (tagName: string) => {
  return (
    _: Key,
    { arg }: { arg: TagUpdateBody },
  ): Promise<TagUpdateOKResponse> => {
    return tagUpdate(tagName, arg);
  };
};
export const getTagUpdateMutationKey = (tagName: string) =>
  [`/tags/${tagName}`] as const;

export type TagUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tagUpdate>>
>;
export type TagUpdateMutationError =
  | BadRequestResponse
  | UnauthorisedResponse
  | ForbiddenResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

export const useTagUpdate = <
  TError =
    | BadRequestResponse
    | UnauthorisedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  tagName: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof tagUpdate>>,
      TError,
      Key,
      TagUpdateBody,
      Awaited<ReturnType<typeof tagUpdate>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getTagUpdateMutationKey(tagName);
  const swrFn = getTagUpdateMutationFetcher(tagName);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
