// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/drivefolder"
	"github.com/rs/xid"
)

// DriveFolderCreate is the builder for creating a DriveFolder entity.
type DriveFolderCreate struct {
	config
	mutation *DriveFolderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DriveFolderCreate) SetCreatedAt(v time.Time) *DriveFolderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DriveFolderCreate) SetNillableCreatedAt(v *time.Time) *DriveFolderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DriveFolderCreate) SetUpdatedAt(v time.Time) *DriveFolderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DriveFolderCreate) SetNillableUpdatedAt(v *time.Time) *DriveFolderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DriveFolderCreate) SetDeletedAt(v time.Time) *DriveFolderCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DriveFolderCreate) SetNillableDeletedAt(v *time.Time) *DriveFolderCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DriveFolderCreate) SetName(v string) *DriveFolderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *DriveFolderCreate) SetDescription(v string) *DriveFolderCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DriveFolderCreate) SetNillableDescription(v *string) *DriveFolderCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDriveFolderID sets the "drive_folder_id" field.
func (_c *DriveFolderCreate) SetDriveFolderID(v string) *DriveFolderCreate {
	_c.mutation.SetDriveFolderID(v)
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *DriveFolderCreate) SetVisibility(v drivefolder.Visibility) *DriveFolderCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *DriveFolderCreate) SetNillableVisibility(v *drivefolder.Visibility) *DriveFolderCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *DriveFolderCreate) SetSort(v int) *DriveFolderCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *DriveFolderCreate) SetNillableSort(v *int) *DriveFolderCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetAddedBy sets the "added_by" field.
func (_c *DriveFolderCreate) SetAddedBy(v xid.ID) *DriveFolderCreate {
	_c.mutation.SetAddedBy(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DriveFolderCreate) SetID(v xid.ID) *DriveFolderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DriveFolderCreate) SetNillableID(v *xid.ID) *DriveFolderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *DriveFolderCreate) SetAccountID(id xid.ID) *DriveFolderCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *DriveFolderCreate) SetAccount(v *Account) *DriveFolderCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the DriveFolderMutation object of the builder.
func (_c *DriveFolderCreate) Mutation() *DriveFolderMutation {
	return _c.mutation
}

// Save creates the DriveFolder in the database.
func (_c *DriveFolderCreate) Save(ctx context.Context) (*DriveFolder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DriveFolderCreate) SaveX(ctx context.Context) *DriveFolder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DriveFolderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DriveFolderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DriveFolderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := drivefolder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := drivefolder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := drivefolder.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := drivefolder.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := drivefolder.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DriveFolderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DriveFolder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DriveFolder.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DriveFolder.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := drivefolder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DriveFolderID(); !ok {
		return &ValidationError{Name: "drive_folder_id", err: errors.New(`ent: missing required field "DriveFolder.drive_folder_id"`)}
	}
	if v, ok := _c.mutation.DriveFolderID(); ok {
		if err := drivefolder.DriveFolderIDValidator(v); err != nil {
			return &ValidationError{Name: "drive_folder_id", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.drive_folder_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "DriveFolder.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := drivefolder.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "DriveFolder.sort"`)}
	}
	if _, ok := _c.mutation.AddedBy(); !ok {
		return &ValidationError{Name: "added_by", err: errors.New(`ent: missing required field "DriveFolder.added_by"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := drivefolder.IDValidator(v.String()); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.id": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "DriveFolder.account"`)}
	}
	return nil
}

func (_c *DriveFolderCreate) sqlSave(ctx context.Context) (*DriveFolder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DriveFolderCreate) createSpec() (*DriveFolder, *sqlgraph.CreateSpec) {
	var (
		_node = &DriveFolder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(drivefolder.Table, sqlgraph.NewFieldSpec(drivefolder.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(drivefolder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(drivefolder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(drivefolder.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(drivefolder.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(drivefolder.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DriveFolderID(); ok {
		_spec.SetField(drivefolder.FieldDriveFolderID, field.TypeString, value)
		_node.DriveFolderID = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(drivefolder.FieldVisibility, field.TypeEnum, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(drivefolder.FieldSort, field.TypeInt, value)
		_node.Sort = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drivefolder.AccountTable,
			Columns: []string{drivefolder.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AddedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DriveFolder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DriveFolderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DriveFolderCreate) OnConflict(opts ...sql.ConflictOption) *DriveFolderUpsertOne {
	_c.conflict = opts
	return &DriveFolderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DriveFolder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DriveFolderCreate) OnConflictColumns(columns ...string) *DriveFolderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DriveFolderUpsertOne{
		create: _c,
	}
}

type (
	// DriveFolderUpsertOne is the builder for "upsert"-ing
	//  one DriveFolder node.
	DriveFolderUpsertOne struct {
		create *DriveFolderCreate
	}

	// DriveFolderUpsert is the "OnConflict" setter.
	DriveFolderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DriveFolderUpsert) SetUpdatedAt(v time.Time) *DriveFolderUpsert {
	u.Set(drivefolder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DriveFolderUpsert) UpdateUpdatedAt() *DriveFolderUpsert {
	u.SetExcluded(drivefolder.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DriveFolderUpsert) SetDeletedAt(v time.Time) *DriveFolderUpsert {
	u.Set(drivefolder.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DriveFolderUpsert) UpdateDeletedAt() *DriveFolderUpsert {
	u.SetExcluded(drivefolder.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DriveFolderUpsert) ClearDeletedAt() *DriveFolderUpsert {
	u.SetNull(drivefolder.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *DriveFolderUpsert) SetName(v string) *DriveFolderUpsert {
	u.Set(drivefolder.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DriveFolderUpsert) UpdateName() *DriveFolderUpsert {
	u.SetExcluded(drivefolder.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *DriveFolderUpsert) SetDescription(v string) *DriveFolderUpsert {
	u.Set(drivefolder.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DriveFolderUpsert) UpdateDescription() *DriveFolderUpsert {
	u.SetExcluded(drivefolder.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *DriveFolderUpsert) ClearDescription() *DriveFolderUpsert {
	u.SetNull(drivefolder.FieldDescription)
	return u
}

// SetDriveFolderID sets the "drive_folder_id" field.
func (u *DriveFolderUpsert) SetDriveFolderID(v string) *DriveFolderUpsert {
	u.Set(drivefolder.FieldDriveFolderID, v)
	return u
}

// UpdateDriveFolderID sets the "drive_folder_id" field to the value that was provided on create.
func (u *DriveFolderUpsert) UpdateDriveFolderID() *DriveFolderUpsert {
	u.SetExcluded(drivefolder.FieldDriveFolderID)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *DriveFolderUpsert) SetVisibility(v drivefolder.Visibility) *DriveFolderUpsert {
	u.Set(drivefolder.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *DriveFolderUpsert) UpdateVisibility() *DriveFolderUpsert {
	u.SetExcluded(drivefolder.FieldVisibility)
	return u
}

// SetSort sets the "sort" field.
func (u *DriveFolderUpsert) SetSort(v int) *DriveFolderUpsert {
	u.Set(drivefolder.FieldSort, v)
	return u
}

// UpdateSort sets the "sort" field to the value that was provided on create.
func (u *DriveFolderUpsert) UpdateSort() *DriveFolderUpsert {
	u.SetExcluded(drivefolder.FieldSort)
	return u
}

// AddSort adds v to the "sort" field.
func (u *DriveFolderUpsert) AddSort(v int) *DriveFolderUpsert {
	u.Add(drivefolder.FieldSort, v)
	return u
}

// SetAddedBy sets the "added_by" field.
func (u *DriveFolderUpsert) SetAddedBy(v xid.ID) *DriveFolderUpsert {
	u.Set(drivefolder.FieldAddedBy, v)
	return u
}

// UpdateAddedBy sets the "added_by" field to the value that was provided on create.
func (u *DriveFolderUpsert) UpdateAddedBy() *DriveFolderUpsert {
	u.SetExcluded(drivefolder.FieldAddedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DriveFolder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(drivefolder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DriveFolderUpsertOne) UpdateNewValues() *DriveFolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(drivefolder.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(drivefolder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DriveFolder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DriveFolderUpsertOne) Ignore() *DriveFolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DriveFolderUpsertOne) DoNothing() *DriveFolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DriveFolderCreate.OnConflict
// documentation for more info.
func (u *DriveFolderUpsertOne) Update(set func(*DriveFolderUpsert)) *DriveFolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DriveFolderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DriveFolderUpsertOne) SetUpdatedAt(v time.Time) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DriveFolderUpsertOne) UpdateUpdatedAt() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DriveFolderUpsertOne) SetDeletedAt(v time.Time) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DriveFolderUpsertOne) UpdateDeletedAt() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DriveFolderUpsertOne) ClearDeletedAt() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *DriveFolderUpsertOne) SetName(v string) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DriveFolderUpsertOne) UpdateName() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *DriveFolderUpsertOne) SetDescription(v string) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DriveFolderUpsertOne) UpdateDescription() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *DriveFolderUpsertOne) ClearDescription() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.ClearDescription()
	})
}

// SetDriveFolderID sets the "drive_folder_id" field.
func (u *DriveFolderUpsertOne) SetDriveFolderID(v string) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetDriveFolderID(v)
	})
}

// UpdateDriveFolderID sets the "drive_folder_id" field to the value that was provided on create.
func (u *DriveFolderUpsertOne) UpdateDriveFolderID() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateDriveFolderID()
	})
}

// SetVisibility sets the "visibility" field.
func (u *DriveFolderUpsertOne) SetVisibility(v drivefolder.Visibility) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *DriveFolderUpsertOne) UpdateVisibility() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateVisibility()
	})
}

// SetSort sets the "sort" field.
func (u *DriveFolderUpsertOne) SetSort(v int) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetSort(v)
	})
}

// AddSort adds v to the "sort" field.
func (u *DriveFolderUpsertOne) AddSort(v int) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.AddSort(v)
	})
}

// UpdateSort sets the "sort" field to the value that was provided on create.
func (u *DriveFolderUpsertOne) UpdateSort() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateSort()
	})
}

// SetAddedBy sets the "added_by" field.
func (u *DriveFolderUpsertOne) SetAddedBy(v xid.ID) *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetAddedBy(v)
	})
}

// UpdateAddedBy sets the "added_by" field to the value that was provided on create.
func (u *DriveFolderUpsertOne) UpdateAddedBy() *DriveFolderUpsertOne {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateAddedBy()
	})
}

// Exec executes the query.
func (u *DriveFolderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DriveFolderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DriveFolderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DriveFolderUpsertOne) ID(ctx context.Context) (id xid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DriveFolderUpsertOne.ID is not supported by MySQL driver. Use DriveFolderUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DriveFolderUpsertOne) IDX(ctx context.Context) xid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DriveFolderCreateBulk is the builder for creating many DriveFolder entities in bulk.
type DriveFolderCreateBulk struct {
	config
	err      error
	builders []*DriveFolderCreate
	conflict []sql.ConflictOption
}

// Save creates the DriveFolder entities in the database.
func (_c *DriveFolderCreateBulk) Save(ctx context.Context) ([]*DriveFolder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DriveFolder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DriveFolderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DriveFolderCreateBulk) SaveX(ctx context.Context) []*DriveFolder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DriveFolderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DriveFolderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DriveFolder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DriveFolderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DriveFolderCreateBulk) OnConflict(opts ...sql.ConflictOption) *DriveFolderUpsertBulk {
	_c.conflict = opts
	return &DriveFolderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DriveFolder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DriveFolderCreateBulk) OnConflictColumns(columns ...string) *DriveFolderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DriveFolderUpsertBulk{
		create: _c,
	}
}

// DriveFolderUpsertBulk is the builder for "upsert"-ing
// a bulk of DriveFolder nodes.
type DriveFolderUpsertBulk struct {
	create *DriveFolderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DriveFolder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(drivefolder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DriveFolderUpsertBulk) UpdateNewValues() *DriveFolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(drivefolder.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(drivefolder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DriveFolder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DriveFolderUpsertBulk) Ignore() *DriveFolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DriveFolderUpsertBulk) DoNothing() *DriveFolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DriveFolderCreateBulk.OnConflict
// documentation for more info.
func (u *DriveFolderUpsertBulk) Update(set func(*DriveFolderUpsert)) *DriveFolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DriveFolderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DriveFolderUpsertBulk) SetUpdatedAt(v time.Time) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DriveFolderUpsertBulk) UpdateUpdatedAt() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DriveFolderUpsertBulk) SetDeletedAt(v time.Time) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DriveFolderUpsertBulk) UpdateDeletedAt() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DriveFolderUpsertBulk) ClearDeletedAt() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *DriveFolderUpsertBulk) SetName(v string) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DriveFolderUpsertBulk) UpdateName() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *DriveFolderUpsertBulk) SetDescription(v string) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DriveFolderUpsertBulk) UpdateDescription() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *DriveFolderUpsertBulk) ClearDescription() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.ClearDescription()
	})
}

// SetDriveFolderID sets the "drive_folder_id" field.
func (u *DriveFolderUpsertBulk) SetDriveFolderID(v string) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetDriveFolderID(v)
	})
}

// UpdateDriveFolderID sets the "drive_folder_id" field to the value that was provided on create.
func (u *DriveFolderUpsertBulk) UpdateDriveFolderID() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateDriveFolderID()
	})
}

// SetVisibility sets the "visibility" field.
func (u *DriveFolderUpsertBulk) SetVisibility(v drivefolder.Visibility) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *DriveFolderUpsertBulk) UpdateVisibility() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateVisibility()
	})
}

// SetSort sets the "sort" field.
func (u *DriveFolderUpsertBulk) SetSort(v int) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetSort(v)
	})
}

// AddSort adds v to the "sort" field.
func (u *DriveFolderUpsertBulk) AddSort(v int) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.AddSort(v)
	})
}

// UpdateSort sets the "sort" field to the value that was provided on create.
func (u *DriveFolderUpsertBulk) UpdateSort() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateSort()
	})
}

// SetAddedBy sets the "added_by" field.
func (u *DriveFolderUpsertBulk) SetAddedBy(v xid.ID) *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.SetAddedBy(v)
	})
}

// UpdateAddedBy sets the "added_by" field to the value that was provided on create.
func (u *DriveFolderUpsertBulk) UpdateAddedBy() *DriveFolderUpsertBulk {
	return u.Update(func(s *DriveFolderUpsert) {
		s.UpdateAddedBy()
	})
}

// Exec executes the query.
func (u *DriveFolderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DriveFolderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DriveFolderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DriveFolderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
