// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/drivefolder"
	"github.com/rs/xid"
)

// DriveFolder is the model entity for the DriveFolder schema.
type DriveFolder struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// DriveFolderID holds the value of the "drive_folder_id" field.
	DriveFolderID string `json:"drive_folder_id,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility drivefolder.Visibility `json:"visibility,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int `json:"sort,omitempty"`
	// AddedBy holds the value of the "added_by" field.
	AddedBy xid.ID `json:"added_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DriveFolderQuery when eager-loading is set.
	Edges        DriveFolderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DriveFolderEdges holds the relations/edges for other nodes in the graph.
type DriveFolderEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DriveFolderEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DriveFolder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case drivefolder.FieldSort:
			values[i] = new(sql.NullInt64)
		case drivefolder.FieldName, drivefolder.FieldDescription, drivefolder.FieldDriveFolderID, drivefolder.FieldVisibility:
			values[i] = new(sql.NullString)
		case drivefolder.FieldCreatedAt, drivefolder.FieldUpdatedAt, drivefolder.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case drivefolder.FieldID, drivefolder.FieldAddedBy:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DriveFolder fields.
func (_m *DriveFolder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case drivefolder.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case drivefolder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case drivefolder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case drivefolder.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case drivefolder.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case drivefolder.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case drivefolder.FieldDriveFolderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field drive_folder_id", values[i])
			} else if value.Valid {
				_m.DriveFolderID = value.String
			}
		case drivefolder.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = drivefolder.Visibility(value.String)
			}
		case drivefolder.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		case drivefolder.FieldAddedBy:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field added_by", values[i])
			} else if value != nil {
				_m.AddedBy = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DriveFolder.
// This includes values selected through modifiers, order, etc.
func (_m *DriveFolder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the DriveFolder entity.
func (_m *DriveFolder) QueryAccount() *AccountQuery {
	return NewDriveFolderClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this DriveFolder.
// Note that you need to call DriveFolder.Unwrap() before calling this method if this DriveFolder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DriveFolder) Update() *DriveFolderUpdateOne {
	return NewDriveFolderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DriveFolder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DriveFolder) Unwrap() *DriveFolder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DriveFolder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DriveFolder) String() string {
	var builder strings.Builder
	builder.WriteString("DriveFolder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("drive_folder_id=")
	builder.WriteString(_m.DriveFolderID)
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(fmt.Sprintf("%v", _m.Visibility))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("added_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.AddedBy))
	builder.WriteByte(')')
	return builder.String()
}

// DriveFolders is a parsable slice of DriveFolder.
type DriveFolders []*DriveFolder
