// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/drivefolder"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/rs/xid"
)

// DriveFolderUpdate is the builder for updating DriveFolder entities.
type DriveFolderUpdate struct {
	config
	hooks     []Hook
	mutation  *DriveFolderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DriveFolderUpdate builder.
func (_u *DriveFolderUpdate) Where(ps ...predicate.DriveFolder) *DriveFolderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DriveFolderUpdate) SetUpdatedAt(v time.Time) *DriveFolderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DriveFolderUpdate) SetDeletedAt(v time.Time) *DriveFolderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DriveFolderUpdate) SetNillableDeletedAt(v *time.Time) *DriveFolderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DriveFolderUpdate) ClearDeletedAt() *DriveFolderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *DriveFolderUpdate) SetName(v string) *DriveFolderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DriveFolderUpdate) SetNillableName(v *string) *DriveFolderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DriveFolderUpdate) SetDescription(v string) *DriveFolderUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DriveFolderUpdate) SetNillableDescription(v *string) *DriveFolderUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DriveFolderUpdate) ClearDescription() *DriveFolderUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDriveFolderID sets the "drive_folder_id" field.
func (_u *DriveFolderUpdate) SetDriveFolderID(v string) *DriveFolderUpdate {
	_u.mutation.SetDriveFolderID(v)
	return _u
}

// SetNillableDriveFolderID sets the "drive_folder_id" field if the given value is not nil.
func (_u *DriveFolderUpdate) SetNillableDriveFolderID(v *string) *DriveFolderUpdate {
	if v != nil {
		_u.SetDriveFolderID(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *DriveFolderUpdate) SetVisibility(v drivefolder.Visibility) *DriveFolderUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *DriveFolderUpdate) SetNillableVisibility(v *drivefolder.Visibility) *DriveFolderUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *DriveFolderUpdate) SetSort(v int) *DriveFolderUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *DriveFolderUpdate) SetNillableSort(v *int) *DriveFolderUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *DriveFolderUpdate) AddSort(v int) *DriveFolderUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetAddedBy sets the "added_by" field.
func (_u *DriveFolderUpdate) SetAddedBy(v xid.ID) *DriveFolderUpdate {
	_u.mutation.SetAddedBy(v)
	return _u
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_u *DriveFolderUpdate) SetNillableAddedBy(v *xid.ID) *DriveFolderUpdate {
	if v != nil {
		_u.SetAddedBy(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *DriveFolderUpdate) SetAccountID(id xid.ID) *DriveFolderUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *DriveFolderUpdate) SetAccount(v *Account) *DriveFolderUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the DriveFolderMutation object of the builder.
func (_u *DriveFolderUpdate) Mutation() *DriveFolderMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *DriveFolderUpdate) ClearAccount() *DriveFolderUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DriveFolderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DriveFolderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DriveFolderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DriveFolderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DriveFolderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := drivefolder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DriveFolderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := drivefolder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DriveFolderID(); ok {
		if err := drivefolder.DriveFolderIDValidator(v); err != nil {
			return &ValidationError{Name: "drive_folder_id", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.drive_folder_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := drivefolder.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.visibility": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DriveFolder.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DriveFolderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DriveFolderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DriveFolderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drivefolder.Table, drivefolder.Columns, sqlgraph.NewFieldSpec(drivefolder.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(drivefolder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(drivefolder.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(drivefolder.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(drivefolder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(drivefolder.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(drivefolder.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DriveFolderID(); ok {
		_spec.SetField(drivefolder.FieldDriveFolderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(drivefolder.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(drivefolder.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(drivefolder.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drivefolder.AccountTable,
			Columns: []string{drivefolder.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drivefolder.AccountTable,
			Columns: []string{drivefolder.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drivefolder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DriveFolderUpdateOne is the builder for updating a single DriveFolder entity.
type DriveFolderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DriveFolderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DriveFolderUpdateOne) SetUpdatedAt(v time.Time) *DriveFolderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DriveFolderUpdateOne) SetDeletedAt(v time.Time) *DriveFolderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DriveFolderUpdateOne) SetNillableDeletedAt(v *time.Time) *DriveFolderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DriveFolderUpdateOne) ClearDeletedAt() *DriveFolderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *DriveFolderUpdateOne) SetName(v string) *DriveFolderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DriveFolderUpdateOne) SetNillableName(v *string) *DriveFolderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DriveFolderUpdateOne) SetDescription(v string) *DriveFolderUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DriveFolderUpdateOne) SetNillableDescription(v *string) *DriveFolderUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DriveFolderUpdateOne) ClearDescription() *DriveFolderUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDriveFolderID sets the "drive_folder_id" field.
func (_u *DriveFolderUpdateOne) SetDriveFolderID(v string) *DriveFolderUpdateOne {
	_u.mutation.SetDriveFolderID(v)
	return _u
}

// SetNillableDriveFolderID sets the "drive_folder_id" field if the given value is not nil.
func (_u *DriveFolderUpdateOne) SetNillableDriveFolderID(v *string) *DriveFolderUpdateOne {
	if v != nil {
		_u.SetDriveFolderID(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *DriveFolderUpdateOne) SetVisibility(v drivefolder.Visibility) *DriveFolderUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *DriveFolderUpdateOne) SetNillableVisibility(v *drivefolder.Visibility) *DriveFolderUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *DriveFolderUpdateOne) SetSort(v int) *DriveFolderUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *DriveFolderUpdateOne) SetNillableSort(v *int) *DriveFolderUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *DriveFolderUpdateOne) AddSort(v int) *DriveFolderUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetAddedBy sets the "added_by" field.
func (_u *DriveFolderUpdateOne) SetAddedBy(v xid.ID) *DriveFolderUpdateOne {
	_u.mutation.SetAddedBy(v)
	return _u
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_u *DriveFolderUpdateOne) SetNillableAddedBy(v *xid.ID) *DriveFolderUpdateOne {
	if v != nil {
		_u.SetAddedBy(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *DriveFolderUpdateOne) SetAccountID(id xid.ID) *DriveFolderUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *DriveFolderUpdateOne) SetAccount(v *Account) *DriveFolderUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the DriveFolderMutation object of the builder.
func (_u *DriveFolderUpdateOne) Mutation() *DriveFolderMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *DriveFolderUpdateOne) ClearAccount() *DriveFolderUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the DriveFolderUpdate builder.
func (_u *DriveFolderUpdateOne) Where(ps ...predicate.DriveFolder) *DriveFolderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DriveFolderUpdateOne) Select(field string, fields ...string) *DriveFolderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DriveFolder entity.
func (_u *DriveFolderUpdateOne) Save(ctx context.Context) (*DriveFolder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DriveFolderUpdateOne) SaveX(ctx context.Context) *DriveFolder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DriveFolderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DriveFolderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DriveFolderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := drivefolder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DriveFolderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := drivefolder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DriveFolderID(); ok {
		if err := drivefolder.DriveFolderIDValidator(v); err != nil {
			return &ValidationError{Name: "drive_folder_id", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.drive_folder_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := drivefolder.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "DriveFolder.visibility": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DriveFolder.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DriveFolderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DriveFolderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DriveFolderUpdateOne) sqlSave(ctx context.Context) (_node *DriveFolder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drivefolder.Table, drivefolder.Columns, sqlgraph.NewFieldSpec(drivefolder.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DriveFolder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drivefolder.FieldID)
		for _, f := range fields {
			if !drivefolder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != drivefolder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(drivefolder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(drivefolder.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(drivefolder.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(drivefolder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(drivefolder.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(drivefolder.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DriveFolderID(); ok {
		_spec.SetField(drivefolder.FieldDriveFolderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(drivefolder.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(drivefolder.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(drivefolder.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drivefolder.AccountTable,
			Columns: []string{drivefolder.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drivefolder.AccountTable,
			Columns: []string{drivefolder.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DriveFolder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drivefolder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
