// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/passwordresettoken"
	"github.com/rs/xid"
)

// PasswordResetTokenCreate is the builder for creating a PasswordResetToken entity.
type PasswordResetTokenCreate struct {
	config
	mutation *PasswordResetTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PasswordResetTokenCreate) SetCreatedAt(v time.Time) *PasswordResetTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PasswordResetTokenCreate) SetNillableCreatedAt(v *time.Time) *PasswordResetTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetJti sets the "jti" field.
func (_c *PasswordResetTokenCreate) SetJti(v string) *PasswordResetTokenCreate {
	_c.mutation.SetJti(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *PasswordResetTokenCreate) SetAccountID(v xid.ID) *PasswordResetTokenCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PasswordResetTokenCreate) SetExpiresAt(v time.Time) *PasswordResetTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *PasswordResetTokenCreate) SetUsedAt(v time.Time) *PasswordResetTokenCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *PasswordResetTokenCreate) SetNillableUsedAt(v *time.Time) *PasswordResetTokenCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PasswordResetTokenCreate) SetID(v xid.ID) *PasswordResetTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PasswordResetTokenCreate) SetNillableID(v *xid.ID) *PasswordResetTokenCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *PasswordResetTokenCreate) SetAccount(v *Account) *PasswordResetTokenCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the PasswordResetTokenMutation object of the builder.
func (_c *PasswordResetTokenCreate) Mutation() *PasswordResetTokenMutation {
	return _c.mutation
}

// Save creates the PasswordResetToken in the database.
func (_c *PasswordResetTokenCreate) Save(ctx context.Context) (*PasswordResetToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PasswordResetTokenCreate) SaveX(ctx context.Context) *PasswordResetToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasswordResetTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasswordResetTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PasswordResetTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := passwordresettoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := passwordresettoken.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PasswordResetTokenCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PasswordResetToken.created_at"`)}
	}
	if _, ok := _c.mutation.Jti(); !ok {
		return &ValidationError{Name: "jti", err: errors.New(`ent: missing required field "PasswordResetToken.jti"`)}
	}
	if v, ok := _c.mutation.Jti(); ok {
		if err := passwordresettoken.JtiValidator(v); err != nil {
			return &ValidationError{Name: "jti", err: fmt.Errorf(`ent: validator failed for field "PasswordResetToken.jti": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "PasswordResetToken.account_id"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "PasswordResetToken.expires_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := passwordresettoken.IDValidator(v.String()); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PasswordResetToken.id": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "PasswordResetToken.account"`)}
	}
	return nil
}

func (_c *PasswordResetTokenCreate) sqlSave(ctx context.Context) (*PasswordResetToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PasswordResetTokenCreate) createSpec() (*PasswordResetToken, *sqlgraph.CreateSpec) {
	var (
		_node = &PasswordResetToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(passwordresettoken.Table, sqlgraph.NewFieldSpec(passwordresettoken.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(passwordresettoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Jti(); ok {
		_spec.SetField(passwordresettoken.FieldJti, field.TypeString, value)
		_node.Jti = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(passwordresettoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(passwordresettoken.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passwordresettoken.AccountTable,
			Columns: []string{passwordresettoken.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasswordResetToken.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasswordResetTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PasswordResetTokenCreate) OnConflict(opts ...sql.ConflictOption) *PasswordResetTokenUpsertOne {
	_c.conflict = opts
	return &PasswordResetTokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasswordResetToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasswordResetTokenCreate) OnConflictColumns(columns ...string) *PasswordResetTokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasswordResetTokenUpsertOne{
		create: _c,
	}
}

type (
	// PasswordResetTokenUpsertOne is the builder for "upsert"-ing
	//  one PasswordResetToken node.
	PasswordResetTokenUpsertOne struct {
		create *PasswordResetTokenCreate
	}

	// PasswordResetTokenUpsert is the "OnConflict" setter.
	PasswordResetTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsedAt sets the "used_at" field.
func (u *PasswordResetTokenUpsert) SetUsedAt(v time.Time) *PasswordResetTokenUpsert {
	u.Set(passwordresettoken.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *PasswordResetTokenUpsert) UpdateUsedAt() *PasswordResetTokenUpsert {
	u.SetExcluded(passwordresettoken.FieldUsedAt)
	return u
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *PasswordResetTokenUpsert) ClearUsedAt() *PasswordResetTokenUpsert {
	u.SetNull(passwordresettoken.FieldUsedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PasswordResetToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passwordresettoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasswordResetTokenUpsertOne) UpdateNewValues() *PasswordResetTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(passwordresettoken.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(passwordresettoken.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Jti(); exists {
			s.SetIgnore(passwordresettoken.FieldJti)
		}
		if _, exists := u.create.mutation.AccountID(); exists {
			s.SetIgnore(passwordresettoken.FieldAccountID)
		}
		if _, exists := u.create.mutation.ExpiresAt(); exists {
			s.SetIgnore(passwordresettoken.FieldExpiresAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasswordResetToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PasswordResetTokenUpsertOne) Ignore() *PasswordResetTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasswordResetTokenUpsertOne) DoNothing() *PasswordResetTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasswordResetTokenCreate.OnConflict
// documentation for more info.
func (u *PasswordResetTokenUpsertOne) Update(set func(*PasswordResetTokenUpsert)) *PasswordResetTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasswordResetTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *PasswordResetTokenUpsertOne) SetUsedAt(v time.Time) *PasswordResetTokenUpsertOne {
	return u.Update(func(s *PasswordResetTokenUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *PasswordResetTokenUpsertOne) UpdateUsedAt() *PasswordResetTokenUpsertOne {
	return u.Update(func(s *PasswordResetTokenUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *PasswordResetTokenUpsertOne) ClearUsedAt() *PasswordResetTokenUpsertOne {
	return u.Update(func(s *PasswordResetTokenUpsert) {
		s.ClearUsedAt()
	})
}

// Exec executes the query.
func (u *PasswordResetTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasswordResetTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasswordResetTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PasswordResetTokenUpsertOne) ID(ctx context.Context) (id xid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PasswordResetTokenUpsertOne.ID is not supported by MySQL driver. Use PasswordResetTokenUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PasswordResetTokenUpsertOne) IDX(ctx context.Context) xid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PasswordResetTokenCreateBulk is the builder for creating many PasswordResetToken entities in bulk.
type PasswordResetTokenCreateBulk struct {
	config
	err      error
	builders []*PasswordResetTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the PasswordResetToken entities in the database.
func (_c *PasswordResetTokenCreateBulk) Save(ctx context.Context) ([]*PasswordResetToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PasswordResetToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasswordResetTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PasswordResetTokenCreateBulk) SaveX(ctx context.Context) []*PasswordResetToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasswordResetTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasswordResetTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasswordResetToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasswordResetTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PasswordResetTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *PasswordResetTokenUpsertBulk {
	_c.conflict = opts
	return &PasswordResetTokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasswordResetToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasswordResetTokenCreateBulk) OnConflictColumns(columns ...string) *PasswordResetTokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasswordResetTokenUpsertBulk{
		create: _c,
	}
}

// PasswordResetTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of PasswordResetToken nodes.
type PasswordResetTokenUpsertBulk struct {
	create *PasswordResetTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PasswordResetToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passwordresettoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasswordResetTokenUpsertBulk) UpdateNewValues() *PasswordResetTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(passwordresettoken.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(passwordresettoken.FieldCreatedAt)
			}
			if _, exists := b.mutation.Jti(); exists {
				s.SetIgnore(passwordresettoken.FieldJti)
			}
			if _, exists := b.mutation.AccountID(); exists {
				s.SetIgnore(passwordresettoken.FieldAccountID)
			}
			if _, exists := b.mutation.ExpiresAt(); exists {
				s.SetIgnore(passwordresettoken.FieldExpiresAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasswordResetToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PasswordResetTokenUpsertBulk) Ignore() *PasswordResetTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasswordResetTokenUpsertBulk) DoNothing() *PasswordResetTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasswordResetTokenCreateBulk.OnConflict
// documentation for more info.
func (u *PasswordResetTokenUpsertBulk) Update(set func(*PasswordResetTokenUpsert)) *PasswordResetTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasswordResetTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *PasswordResetTokenUpsertBulk) SetUsedAt(v time.Time) *PasswordResetTokenUpsertBulk {
	return u.Update(func(s *PasswordResetTokenUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *PasswordResetTokenUpsertBulk) UpdateUsedAt() *PasswordResetTokenUpsertBulk {
	return u.Update(func(s *PasswordResetTokenUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *PasswordResetTokenUpsertBulk) ClearUsedAt() *PasswordResetTokenUpsertBulk {
	return u.Update(func(s *PasswordResetTokenUpsert) {
		s.ClearUsedAt()
	})
}

// Exec executes the query.
func (u *PasswordResetTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PasswordResetTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasswordResetTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasswordResetTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
