// Code generated by ent, DO NOT EDIT.

package drivefolder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldDescription, v))
}

// DriveFolderID applies equality check predicate on the "drive_folder_id" field. It's identical to DriveFolderIDEQ.
func DriveFolderID(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldDriveFolderID, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldSort, v))
}

// AddedBy applies equality check predicate on the "added_by" field. It's identical to AddedByEQ.
func AddedBy(v xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldAddedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldContainsFold(FieldDescription, v))
}

// DriveFolderIDEQ applies the EQ predicate on the "drive_folder_id" field.
func DriveFolderIDEQ(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldDriveFolderID, v))
}

// DriveFolderIDNEQ applies the NEQ predicate on the "drive_folder_id" field.
func DriveFolderIDNEQ(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldDriveFolderID, v))
}

// DriveFolderIDIn applies the In predicate on the "drive_folder_id" field.
func DriveFolderIDIn(vs ...string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldDriveFolderID, vs...))
}

// DriveFolderIDNotIn applies the NotIn predicate on the "drive_folder_id" field.
func DriveFolderIDNotIn(vs ...string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldDriveFolderID, vs...))
}

// DriveFolderIDGT applies the GT predicate on the "drive_folder_id" field.
func DriveFolderIDGT(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldDriveFolderID, v))
}

// DriveFolderIDGTE applies the GTE predicate on the "drive_folder_id" field.
func DriveFolderIDGTE(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldDriveFolderID, v))
}

// DriveFolderIDLT applies the LT predicate on the "drive_folder_id" field.
func DriveFolderIDLT(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldDriveFolderID, v))
}

// DriveFolderIDLTE applies the LTE predicate on the "drive_folder_id" field.
func DriveFolderIDLTE(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldDriveFolderID, v))
}

// DriveFolderIDContains applies the Contains predicate on the "drive_folder_id" field.
func DriveFolderIDContains(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldContains(FieldDriveFolderID, v))
}

// DriveFolderIDHasPrefix applies the HasPrefix predicate on the "drive_folder_id" field.
func DriveFolderIDHasPrefix(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldHasPrefix(FieldDriveFolderID, v))
}

// DriveFolderIDHasSuffix applies the HasSuffix predicate on the "drive_folder_id" field.
func DriveFolderIDHasSuffix(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldHasSuffix(FieldDriveFolderID, v))
}

// DriveFolderIDEqualFold applies the EqualFold predicate on the "drive_folder_id" field.
func DriveFolderIDEqualFold(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEqualFold(FieldDriveFolderID, v))
}

// DriveFolderIDContainsFold applies the ContainsFold predicate on the "drive_folder_id" field.
func DriveFolderIDContainsFold(v string) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldContainsFold(FieldDriveFolderID, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v Visibility) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v Visibility) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...Visibility) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...Visibility) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldVisibility, vs...))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldSort, v))
}

// AddedByEQ applies the EQ predicate on the "added_by" field.
func AddedByEQ(v xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldEQ(FieldAddedBy, v))
}

// AddedByNEQ applies the NEQ predicate on the "added_by" field.
func AddedByNEQ(v xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNEQ(FieldAddedBy, v))
}

// AddedByIn applies the In predicate on the "added_by" field.
func AddedByIn(vs ...xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldIn(FieldAddedBy, vs...))
}

// AddedByNotIn applies the NotIn predicate on the "added_by" field.
func AddedByNotIn(vs ...xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldNotIn(FieldAddedBy, vs...))
}

// AddedByGT applies the GT predicate on the "added_by" field.
func AddedByGT(v xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGT(FieldAddedBy, v))
}

// AddedByGTE applies the GTE predicate on the "added_by" field.
func AddedByGTE(v xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldGTE(FieldAddedBy, v))
}

// AddedByLT applies the LT predicate on the "added_by" field.
func AddedByLT(v xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLT(FieldAddedBy, v))
}

// AddedByLTE applies the LTE predicate on the "added_by" field.
func AddedByLTE(v xid.ID) predicate.DriveFolder {
	return predicate.DriveFolder(sql.FieldLTE(FieldAddedBy, v))
}

// AddedByContains applies the Contains predicate on the "added_by" field.
func AddedByContains(v xid.ID) predicate.DriveFolder {
	vc := v.String()
	return predicate.DriveFolder(sql.FieldContains(FieldAddedBy, vc))
}

// AddedByHasPrefix applies the HasPrefix predicate on the "added_by" field.
func AddedByHasPrefix(v xid.ID) predicate.DriveFolder {
	vc := v.String()
	return predicate.DriveFolder(sql.FieldHasPrefix(FieldAddedBy, vc))
}

// AddedByHasSuffix applies the HasSuffix predicate on the "added_by" field.
func AddedByHasSuffix(v xid.ID) predicate.DriveFolder {
	vc := v.String()
	return predicate.DriveFolder(sql.FieldHasSuffix(FieldAddedBy, vc))
}

// AddedByEqualFold applies the EqualFold predicate on the "added_by" field.
func AddedByEqualFold(v xid.ID) predicate.DriveFolder {
	vc := v.String()
	return predicate.DriveFolder(sql.FieldEqualFold(FieldAddedBy, vc))
}

// AddedByContainsFold applies the ContainsFold predicate on the "added_by" field.
func AddedByContainsFold(v xid.ID) predicate.DriveFolder {
	vc := v.String()
	return predicate.DriveFolder(sql.FieldContainsFold(FieldAddedBy, vc))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.DriveFolder {
	return predicate.DriveFolder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.DriveFolder {
	return predicate.DriveFolder(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DriveFolder) predicate.DriveFolder {
	return predicate.DriveFolder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DriveFolder) predicate.DriveFolder {
	return predicate.DriveFolder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DriveFolder) predicate.DriveFolder {
	return predicate.DriveFolder(sql.NotPredicates(p))
}
