/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import type { StatisticsCategoryPoint } from "./statisticsCategoryPoint";
import type { StatisticsContributor } from "./statisticsContributor";
import type { StatisticsEmojiPoint } from "./statisticsEmojiPoint";
import type { StatisticsFachsemesterPoint } from "./statisticsFachsemesterPoint";
import type { StatisticsHourPoint } from "./statisticsHourPoint";
import type { StatisticsSemesterPoint } from "./statisticsSemesterPoint";
import type { StatisticsSeriesPoint } from "./statisticsSeriesPoint";
import type { StatisticsTagPoint } from "./statisticsTagPoint";
import type { StatisticsThreadPoint } from "./statisticsThreadPoint";
import type { StatisticsTotals } from "./statisticsTotals";
import type { StatisticsTrends } from "./statisticsTrends";
import type { StatisticsWeekdayPoint } from "./statisticsWeekdayPoint";

export type AdminStatistics200 = {
  /** New accounts per day, most recent 30 days. */
  accountsDaily: StatisticsSeriesPoint[];
  /** New accounts per month, most recent 12 months. */
  accountsMonthly: StatisticsSeriesPoint[];
  /** New accounts per year, most recent 5 years. */
  accountsYearly: StatisticsSeriesPoint[];
  /** Distinct accounts that authored a post (thread or
reply) per day, most recent 30 days.
 */
  activeAccountsDaily: StatisticsSeriesPoint[];
  /** Distinct accounts that authored a post per month, most
recent 12 months.
 */
  activeAccountsMonthly: StatisticsSeriesPoint[];
  /** Distinct accounts that authored a post per year, most
recent 5 years.
 */
  activeAccountsYearly: StatisticsSeriesPoint[];
  /** Total files uploaded by members currently recorded in
each study semester (1-11), plus a bucket for members
with no recorded semester and a bucket for members who
have finished ("Fertig"). Shows which cohorts are
contributing the most and least material.
 */
  assetsByFachsemester: StatisticsFachsemesterPoint[];
  /** New file uploads per day, most recent 30 days. */
  assetsDaily: StatisticsSeriesPoint[];
  /** New file uploads per month, most recent 12 months. */
  assetsMonthly: StatisticsSeriesPoint[];
  /** New file uploads per year, most recent 5 years. */
  assetsYearly: StatisticsSeriesPoint[];
  /** New likes per day, most recent 30 days. */
  likesDaily: StatisticsSeriesPoint[];
  /** New likes per month, most recent 12 months. */
  likesMonthly: StatisticsSeriesPoint[];
  /** New likes per year, most recent 5 years. */
  likesYearly: StatisticsSeriesPoint[];
  /** New sessions bucketed by hour of day (0-23, in the
Europe/Berlin time zone), most recent 5 years, to
reveal peak login times.
 */
  loginsByHour: StatisticsHourPoint[];
  /** New sessions bucketed by weekday (1=Monday..7=Sunday,
Europe/Berlin), most recent 5 years, to reveal peak
login days.
 */
  loginsByWeekday: StatisticsWeekdayPoint[];
  /** New sessions per day, most recent 30 days. Approximates
logins; a session is also created on account signup, so
days with many new signups show elevated counts.
 */
  loginsDaily: StatisticsSeriesPoint[];
  /** New sessions per month, most recent 12 months. See
loginsDaily for the signup-session caveat.
 */
  loginsMonthly: StatisticsSeriesPoint[];
  /** New sessions per year, most recent 5 years. See
loginsDaily for the signup-session caveat.
 */
  loginsYearly: StatisticsSeriesPoint[];
  /** New emoji reactions per day, most recent 30 days. */
  reactsDaily: StatisticsSeriesPoint[];
  /** New emoji reactions per month, most recent 12 months. */
  reactsMonthly: StatisticsSeriesPoint[];
  /** New emoji reactions per year, most recent 5 years. */
  reactsYearly: StatisticsSeriesPoint[];
  /** Total threads authored by members currently recorded in
each study semester (1-11), plus a bucket for members
with no recorded semester and a bucket for members who
have finished ("Fertig"). Shows which cohorts are the
most and least engaged.
 */
  threadsByFachsemester: StatisticsFachsemesterPoint[];
  /** New threads per academic term, most recent 8 terms. */
  threadsBySemester: StatisticsSemesterPoint[];
  /** New threads per day, most recent 30 days. */
  threadsDaily: StatisticsSeriesPoint[];
  /** New threads per month, most recent 12 months. */
  threadsMonthly: StatisticsSeriesPoint[];
  /** New threads per year, most recent 5 years. */
  threadsYearly: StatisticsSeriesPoint[];
  /** The most active forum categories by new thread count,
most recent 5 years.
 */
  topCategories: StatisticsCategoryPoint[];
  /** The most active thread authors, most recent 5 years,
with their study semester and most recent thread date.
 */
  topContributors: StatisticsContributor[];
  /** The most used reaction emojis, most recent 5 years. */
  topEmojis: StatisticsEmojiPoint[];
  /** Threads whose opening post received the most likes,
most recent 5 years.
 */
  topLikedThreads: StatisticsThreadPoint[];
  /** The tags carried by the most threads, most recent 5 years. */
  topTags: StatisticsTagPoint[];
  totals: StatisticsTotals;
  trends: StatisticsTrends;
};
