/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import type { StatisticsContributor } from "./statisticsContributor";
import type { StatisticsFachsemesterPoint } from "./statisticsFachsemesterPoint";
import type { StatisticsSemesterPoint } from "./statisticsSemesterPoint";
import type { StatisticsSeriesPoint } from "./statisticsSeriesPoint";
import type { StatisticsTotals } from "./statisticsTotals";

export type AdminStatistics200 = {
  /** New accounts per day, most recent 30 days. */
  accountsDaily: StatisticsSeriesPoint[];
  /** New accounts per month, most recent 12 months. */
  accountsMonthly: StatisticsSeriesPoint[];
  /** New accounts per year, most recent 5 years. */
  accountsYearly: StatisticsSeriesPoint[];
  /** Total files uploaded by members currently recorded in
each study semester (1-11), plus a bucket for members
with no recorded semester and a bucket for members who
have finished ("Fertig"). Shows which cohorts are
contributing the most and least material.
 */
  assetsByFachsemester: StatisticsFachsemesterPoint[];
  /** Total threads authored by members currently recorded in
each study semester (1-11), plus a bucket for members
with no recorded semester and a bucket for members who
have finished ("Fertig"). Shows which cohorts are the
most and least engaged.
 */
  threadsByFachsemester: StatisticsFachsemesterPoint[];
  /** New threads per academic term, most recent 8 terms. */
  threadsBySemester: StatisticsSemesterPoint[];
  /** New threads per day, most recent 30 days. */
  threadsDaily: StatisticsSeriesPoint[];
  /** New threads per month, most recent 12 months. */
  threadsMonthly: StatisticsSeriesPoint[];
  /** New threads per year, most recent 5 years. */
  threadsYearly: StatisticsSeriesPoint[];
  /** The most active thread authors, most recent 5 years,
with their study semester and most recent thread date.
 */
  topContributors: StatisticsContributor[];
  totals: StatisticsTotals;
};
