/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */

export interface AssetServiceSettings {
  /**
   * The maximum size, in megabytes, of a single file upload (attachments,
cover images, plugin archives, etc). Requests with a larger body are
rejected before the file is written to storage. Bound to 1024 MB
(1 GB) to keep this within sane resource limits for most deployments.

   * @minimum 1
   * @maximum 1024
   */
  max_upload_size_mb?: number;
}
