/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */

export interface ContentServiceSettings {
  /**
   * How many replies are returned per page of a thread. Lowering this
keeps long threads fast to load. Changing it alters which page a
given reply lives on, invalidating existing deep links.

   * @minimum 1
   * @maximum 200
   */
  replies_per_page?: number;
  /**
   * How many threads are returned per page of a thread list or feed.

   * @minimum 1
   * @maximum 100
   */
  threads_per_page?: number;
}
