/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import type { Asset } from "./asset";

/**
 * Indicates the search term was found inside the extracted text content
of an asset (e.g. a PDF or image) attached to this item, rather than
in the item's own body text.

 */
export interface DatagraphAssetMatch {
  asset: Asset;
  /** A short snippet of the asset's extracted text surrounding the first match. */
  excerpt: string;
}
