/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import type { DriveChildIDQueryParameter } from "./driveChildIDQueryParameter";
import type { DrivePageTokenQueryParameter } from "./drivePageTokenQueryParameter";

export type DriveFolderContentsParams = {
  /**
 * Google Drive ID of a folder beneath the registered root. Omit to list
the root itself.

 */
  child_id?: DriveChildIDQueryParameter;
  /**
   * Opaque continuation token from a previous listing.
   */
  page_token?: DrivePageTokenQueryParameter;
};
