/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */

/**
 * Where the active Google Drive service account credentials came from,
if any: not configured at all, the environment configuration
(`GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON`/`_FILE`), or uploaded via the
admin interface. An upload takes precedence over the environment.

 */
export type DriveCredentialsSource =
  (typeof DriveCredentialsSource)[keyof typeof DriveCredentialsSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DriveCredentialsSource = {
  none: "none",
  environment: "environment",
  upload: "upload",
} as const;
