/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */

export interface DriveEntry {
  id: string;
  is_folder: boolean;
  /** The type the bytes are served as. Google-native documents report
their exported type, not the Drive type, because that is what a
download or preview actually receives.
 */
  mime_type: string;
  modified_at?: string;
  name: string;
  /** Whether the file can be rendered in the browser. */
  previewable: boolean;
  /** Absent for Google-native documents, whose size is unknown until exported. */
  size?: number;
}
