/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */

export interface InvitationInitialProps {
  /** The point in time after which this invitation may no longer be used. Omit for an invitation that never expires. */
  expires_at?: string;
  /** The maximum number of accounts that may register using this invitation. Omit for unlimited uses. */
  max_uses?: number;
  message?: string;
}
