/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */

export interface SessionServiceSettings {
  /**
   * How long a session without "remember me" survives without activity.
The window slides forward while the member keeps making requests, so
this is an inactivity timeout rather than a hard cap from sign-in.

   * @minimum 1
   * @maximum 43200
   */
  idle_timeout_minutes?: number;
  /**
   * Session lifetime applied when a member signs in with "remember me"
and has not chosen their own duration.

   * @minimum 1
   * @maximum 365
   */
  remember_me_default_days?: number;
  /**
   * Upper bound for member-chosen "remember me" durations. Requests for
longer sessions are clamped to this value.

   * @minimum 1
   * @maximum 365
   */
  remember_me_max_days?: number;
}
