/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import type { CreatedAt } from "./createdAt";
import type { Identifier } from "./identifier";

/**
 * A member ranked by thread activity, for admin review.
 */
export interface StatisticsContributor {
  accountId: Identifier;
  /** The member's handle. */
  handle: string;
  lastThreadAt: CreatedAt;
  /** The member's display name. */
  name: string;
  /** The member's currently recorded study semester (1-12), zero if
not recorded, or -1 if the member has finished ("Fertig").
 */
  semester: number;
  /** Total threads authored by this member in the window. */
  threadCount: number;
}
