/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */

export interface StatisticsTotals {
  /** Total number of registered accounts. */
  accounts: number;
  /** Distinct accounts that authored a post in the last 30 days. */
  activeAccounts30d: number;
  /** Distinct accounts that authored a post in the last 7 days. */
  activeAccounts7d: number;
  /** Total number of categories. */
  categories: number;
  /** Total number of replies (non-root posts). */
  replies: number;
  /** Sessions that are not revoked and not yet expired. */
  sessionsActive: number;
  /** Sessions that are not revoked but have passed their expiry. */
  sessionsExpired: number;
  /** Sessions that were explicitly revoked (e.g. by sign-out). */
  sessionsRevoked: number;
  /** Total number of threads (root posts). */
  threads: number;
}
