/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import type {
  AdminDriveFolderCreateBody,
  AdminDriveFolderUpdateBody,
  DriveFileDownloadOKResponse,
  DriveFileDownloadParams,
  DriveFolderContentsOKResponse,
  DriveFolderContentsParams,
  DriveFolderGetOKResponse,
  DriveFolderListOKResponse,
} from "../openapi-schema";
import { fetcher } from "../server";

/**
 * List every Google Drive folder registered on this installation,
including those hidden from ordinary members.

 */
export type adminDriveFolderListResponse = {
  data: DriveFolderListOKResponse;
  status: number;
};

export const getAdminDriveFolderListUrl = () => {
  return `/admin/drive/folders`;
};

export const adminDriveFolderList = async (
  options?: RequestInit,
): Promise<adminDriveFolderListResponse> => {
  return fetcher<Promise<adminDriveFolderListResponse>>(
    getAdminDriveFolderListUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Register a Google Drive folder so members can browse it. The folder must
already be shared with the installation's service account.

 */
export type adminDriveFolderCreateResponse = {
  data: DriveFolderGetOKResponse;
  status: number;
};

export const getAdminDriveFolderCreateUrl = () => {
  return `/admin/drive/folders`;
};

export const adminDriveFolderCreate = async (
  adminDriveFolderCreateBody: AdminDriveFolderCreateBody,
  options?: RequestInit,
): Promise<adminDriveFolderCreateResponse> => {
  return fetcher<Promise<adminDriveFolderCreateResponse>>(
    getAdminDriveFolderCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(adminDriveFolderCreateBody),
    },
  );
};

/**
 * Change a registered Google Drive folder.
 */
export type adminDriveFolderUpdateResponse = {
  data: DriveFolderGetOKResponse;
  status: number;
};

export const getAdminDriveFolderUpdateUrl = (driveFolderId: string) => {
  return `/admin/drive/folders/${driveFolderId}`;
};

export const adminDriveFolderUpdate = async (
  driveFolderId: string,
  adminDriveFolderUpdateBody: AdminDriveFolderUpdateBody,
  options?: RequestInit,
): Promise<adminDriveFolderUpdateResponse> => {
  return fetcher<Promise<adminDriveFolderUpdateResponse>>(
    getAdminDriveFolderUpdateUrl(driveFolderId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(adminDriveFolderUpdateBody),
    },
  );
};

/**
 * Withdraw a Google Drive folder from the site. Nothing is removed from
Google Drive itself.

 */
export type adminDriveFolderDeleteResponse = {
  data: void;
  status: number;
};

export const getAdminDriveFolderDeleteUrl = (driveFolderId: string) => {
  return `/admin/drive/folders/${driveFolderId}`;
};

export const adminDriveFolderDelete = async (
  driveFolderId: string,
  options?: RequestInit,
): Promise<adminDriveFolderDeleteResponse> => {
  return fetcher<Promise<adminDriveFolderDeleteResponse>>(
    getAdminDriveFolderDeleteUrl(driveFolderId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * List the Google Drive folders the caller may browse. Folders are
filtered by the visibility an administrator assigned to each one.

 */
export type driveFolderListResponse = {
  data: DriveFolderListOKResponse;
  status: number;
};

export const getDriveFolderListUrl = () => {
  return `/drive/folders`;
};

export const driveFolderList = async (
  options?: RequestInit,
): Promise<driveFolderListResponse> => {
  return fetcher<Promise<driveFolderListResponse>>(getDriveFolderListUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * List the contents of a registered folder, or of a folder beneath it.
Any folder outside the registered root is reported as not found.

 */
export type driveFolderContentsResponse = {
  data: DriveFolderContentsOKResponse;
  status: number;
};

export const getDriveFolderContentsUrl = (
  driveFolderId: string,
  params?: DriveFolderContentsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  return normalizedParams.size
    ? `/drive/folders/${driveFolderId}/contents?${normalizedParams.toString()}`
    : `/drive/folders/${driveFolderId}/contents`;
};

export const driveFolderContents = async (
  driveFolderId: string,
  params?: DriveFolderContentsParams,
  options?: RequestInit,
): Promise<driveFolderContentsResponse> => {
  return fetcher<Promise<driveFolderContentsResponse>>(
    getDriveFolderContentsUrl(driveFolderId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Stream a file's contents through the site. Google-native documents are
exported to a portable format first. Any file outside the registered
root is reported as not found.

 */
export type driveFileDownloadResponse = {
  data: DriveFileDownloadOKResponse;
  status: number;
};

export const getDriveFileDownloadUrl = (
  driveFolderId: string,
  driveFileId: string,
  params?: DriveFileDownloadParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  return normalizedParams.size
    ? `/drive/folders/${driveFolderId}/files/${driveFileId}/content?${normalizedParams.toString()}`
    : `/drive/folders/${driveFolderId}/files/${driveFileId}/content`;
};

export const driveFileDownload = async (
  driveFolderId: string,
  driveFileId: string,
  params?: DriveFileDownloadParams,
  options?: RequestInit,
): Promise<driveFileDownloadResponse> => {
  return fetcher<Promise<driveFileDownloadResponse>>(
    getDriveFileDownloadUrl(driveFolderId, driveFileId, params),
    {
      ...options,
      method: "GET",
    },
  );
};
