/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.26.13-post
 */
import type {
  TagCreateBody,
  TagCreateOKResponse,
  TagGetOKResponse,
  TagListOKResponse,
  TagListParams,
} from "../openapi-schema";
import { fetcher } from "../server";

/**
 * Get a list of all tags on the site.
 */
export type tagListResponse = {
  data: TagListOKResponse;
  status: number;
};

export const getTagListUrl = (params?: TagListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  return normalizedParams.size
    ? `/tags?${normalizedParams.toString()}`
    : `/tags`;
};

export const tagList = async (
  params?: TagListParams,
  options?: RequestInit,
): Promise<tagListResponse> => {
  return fetcher<Promise<tagListResponse>>(getTagListUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * Create a new tag. Visible to staff/moderators.
 */
export type tagCreateResponse = {
  data: TagCreateOKResponse;
  status: number;
};

export const getTagCreateUrl = () => {
  return `/tags`;
};

export const tagCreate = async (
  tagCreateBody: TagCreateBody,
  options?: RequestInit,
): Promise<tagCreateResponse> => {
  return fetcher<Promise<tagCreateResponse>>(getTagCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(tagCreateBody),
  });
};

/**
 * Get information about a tag.
 */
export type tagGetResponse = {
  data: TagGetOKResponse;
  status: number;
};

export const getTagGetUrl = (tagName: string) => {
  return `/tags/${tagName}`;
};

export const tagGet = async (
  tagName: string,
  options?: RequestInit,
): Promise<tagGetResponse> => {
  return fetcher<Promise<tagGetResponse>>(getTagGetUrl(tagName), {
    ...options,
    method: "GET",
  });
};

/**
 * Delete a tag by name. Visible to staff/moderators.
 */
export type tagDeleteResponse = {
  data: void;
  status: number;
};

export const getTagDeleteUrl = (tagName: string) => {
  return `/tags/${tagName}`;
};

export const tagDelete = async (
  tagName: string,
  options?: RequestInit,
): Promise<tagDeleteResponse> => {
  return fetcher<Promise<tagDeleteResponse>>(getTagDeleteUrl(tagName), {
    ...options,
    method: "DELETE",
  });
};
